swagger: '2.0'

info:
  version: 1.0.0
  title: Test API
  description: API Test.

schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /test:
    get:
      tags: ["test"]
      operationId: getTest
      parameters:
        - in: query
          name: id
          type: integer
          format: int64
      responses:
        '200':
          description: "123"
          schema:
            type: integer