// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API Test.",
    "title": "Test API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/test": {
      "get": {
        "tags": [
          "test"
        ],
        "operationId": "getTest",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "123",
            "schema": {
              "type": "integer"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API Test.",
    "title": "Test API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/test": {
      "get": {
        "tags": [
          "test"
        ],
        "operationId": "getTest",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "123",
            "schema": {
              "type": "integer"
            }
          }
        }
      }
    }
  }
}`))
}
